FROM --platform=linux/arm64 node:20-alpine

WORKDIR /app

# 必要なパッケージをインストール（OpenSSLを含む）
RUN apk add --no-cache \
    openssl \
    libssl3 \
    libcrypto3 \
    libc6-compat

# パッケージ管理ファイルをコピー
COPY package*.json ./

# 依存関係のインストール
RUN npm install
RUN npm install ts-node typescript @prisma/client prisma

# ソースコードのコピー
COPY . .

COPY prisma ./prisma
COPY .env ./

# Prisma Clientの生成
RUN npx prisma generate

# 開発サーバーの起動
CMD ["npm", "run", "dev"]
